[package]
name = "music-randomizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brstm = { path = ".." }
binrw = "0.10.0"
thiserror = "1.0.37"
clap = { version = "4.0.8", features = ["derive"] }
rand = "0.8.5"
rand_pcg = "0.3.1"
